AWSTemplateFormatVersion: 2010-09-09
Parameters:

    VpcId:
        Description: Select VPC ID
        Type: AWS::EC2::VPC::Id
    SubnetId:
        Description: Select Subnet ID.
        Type: AWS::EC2::Subnet::Id
    InstanceType:
        Description: Select Instance Type.
        Type: String
        AllowedValues: 
        - t2.medium
        - t2.micro
        - t2.nano
        - t2.small
        - t2.xlarge
    KeyName:
    	Description: Enter Name of pem key.
    	Type: String
    	Default: mykey
Resources:  
  
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Web server
      GroupName: web     
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          
  MyEc2:
    Type: 'AWS::EC2::Instance'
    DependsOn: WebSecurityGroup
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-06489866022e12a14
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref WebSecurityGroup
        
